<a href="https://colab.research.google.com/github/sangetha959764-ship-it/MINI-PROJECT-1/blob/main/MINI_PROJECT_1(EARTHQUAKES).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EARTHQUAKE DATA PROJECT**

**(Python , Pandas, SQL)**

by sangeetha j

#  Dataset retrival

In [ ]:
import requests
import pandas as pd
from datetime import datetime

In [ ]:
url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_records = []
start_year = datetime.now().year - 5
end_year = datetime.now().year


for year in range(start_year, end_year + 1):
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        params = {
    "format": "geojson",
    "starttime": start_date,
    "endtime": end_date,
    "minmagnitude": 3
     }


        response = requests.get(url, params=params)
        if response.status_code != 200:
            print(f"{start_date}: {response.text[:200]}")
            continue

        try:
            data = response.json()
        except Exception as e:
            print(f"{start_date}: {e}")
            continue

        for f in data["features"]:
            p = f["properties"]
            g = f["geometry"]["coordinates"]
            all_records.append({
                "id": f.get("id"),
                "time": pd.to_datetime(p.get("time"), unit="ms"),
                "updated": pd.to_datetime(p.get("updated"), unit="ms"),
                "latitude": g[1] if g else None,
                "longitude": g[0] if g else None,
                "depth_km": g[2] if g else None,
                "mag": p.get("mag"),
                "mag-type": p.get("mag-type"),
                "place": p.get("place"),
                "status": p.get("status") ,
                "tsunami": p.get("tsunami"),
                "sig": p.get("sig"),
                "net": p.get("net"),
                "nst": p.get("nst"),
                "dmin": p.get("dmin"),
                "rms": p.get("rms"),
                "gap": p.get("gap"),
                "mag error": p.get("mag error"),
                "depth error": p.get("depth error"),
                "magnst": p.get("magnst"),
                "location source": p.get("location source"),
                "mag source": p.get("mag source"),
                "types": p.get("types"),
                "ids": p.get("ids"),
                "sources": p.get("sources"),
                "type": p.get("type"),

            })


df = pd.DataFrame(all_records)
df
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 108687
Columns: 26

# Read the csv file using pandas

In [ ]:
data = 'earthquake.csv'
df.to_csv(data , index = False)

In [ ]:
df = pd.read_csv('/content/earthquake.csv')
df

,id,time,updated,latitude,longitude,depth_km,mag,mag-type,place,status,...,gap,mag error,depth error,magnst,location source,mag source,types,ids,sources,type
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.270,4.7,NaN,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,42.0,NaN,NaN,NaN,NaN,NaN,",dyfi,moment-tensor,origin,phase-data,",",us6000ddi8,",",us,",earthquake
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.710,4.1,NaN,Fiji region,reviewed,...,64.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us6000dev6,",",us,",earthquake
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.730,4.7,NaN,"103 km SW of Basco, Philippines",reviewed,...,106.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us6000dev5,",",us,",earthquake
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.000,4.9,NaN,"114 km N of M?n?b, Iran",reviewed,...,71.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us6000ddhs,",",us,",earthquake
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.000,4.0,NaN,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,65.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us6000dev4,",",us,",earthquake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108682,us6000sg1v,2026-03-01 00:41:53.193,2026-03-20 02:51:25.040,-10.7303,164.3618,10.000,4.5,NaN,"157 km W of Lata, Solomon Islands",reviewed,...,129.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us6000sg1v,",",us,",earthquake
108683,us7000s15b,2026-03-01 00:35:07.786,2026-03-01 02:09:18.040,31.4169,131.3253,56.324,4.4,NaN,"11 km SE of Kushima, Japan",reviewed,...,88.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us7000s15b,",",us,",earthquake
108684,us7000s15a,2026-03-01 00:25:44.225,2026-03-21 22:07:39.040,-9.9104,119.9576,61.556,4.5,NaN,"43 km SW of Waingapu, Indonesia",reviewed,...,93.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us7000s15a,",",us,",earthquake
108685,us6000sg1m,2026-03-01 00:22:43.082,2026-03-21 01:12:28.040,-24.0653,179.7641,537.793,4.1,NaN,south of the Fiji Islands,reviewed,...,182.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us6000sg1m,",",us,",earthquake
108686,us7000s159,2026-03-01 00:15:07.581,2026-03-21 21:53:45.040,51.6781,158.0044,76.238,4.3,NaN,"106 km E of Ozernovskiy, Russia",reviewed,...,134.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us7000s159,",",us,",earthquake

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108687 entries, 0 to 108686
Data columns (total 26 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               108687 non-null  object
 1   time             108687 non-null  object
 2   updated          108687 non-null  object
 3   latitude         108687 non-null  float64
 4   longitude        108687 non-null  float64
 5   depth_km         108687 non-null  float64
 6   mag              108687 non-null  float64
 7   mag-type         0 non-null       float64
 8   place            108687 non-null  object
 9   status           108687 non-null  object
 10  tsunami          108687 non-null  int64
 11  sig              108687 non-null  int64
 12  net              108687 non-null  object
 13  nst              80926 non-null   float64
 14  dmin             104713 non-null  float64
 15  rms              108669 non-null  float64
 16  gap              105666 non-null  float64
 17  mag error        0 non-null       float64
 18  depth error      0 non-null       float64
 19  magnst           0 non-null       float64
 20  location source  0 non-null       float64
 21  mag source       0 non-null       float64
 22  types            108687 non-null  object
 23  ids              108687 non-null  object
 24  sources          108687 non-null  object
 25  type             108687 non-null  object
dtypes: float64(14), int64(2), object(10)
memory usage: 21.6+ MB

change the datatype(time,updated)

In [ ]:
df['time'] = pd.to_datetime(df['time'])
df['updated'] = pd.to_datetime(df['updated'])

#Clean Text file

In [ ]:
import re
df['place'] = df['place'].str.extract(r',\s*([A-Za-z]+)$')
df['place']

0           Argentina
1                 NaN
2         Philippines
3                Iran
4                 NaN
             ...
108682            NaN
108683          Japan
108684      Indonesia
108685            NaN
108686         Russia
Name: place, Length: 108687, dtype: object

In [ ]:
df['status'].fillna(df['status'].mode()[0], inplace=True)
df['net'].fillna(df['net'].mode()[0], inplace=True)
df['types'].fillna(df['types'].mode()[0], inplace=True)
df['ids'].fillna(df['ids'].mode()[0], inplace=True)
df['sources'].fillna(df['sources'].mode()[0], inplace=True)
df['type'].fillna(df['type'].mode()[0], inplace=True)
df['place'].fillna(df['place'].mode()[0], inplace=True)

/tmp/ipykernel_30065/3345114217.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['status'].fillna(df['status'].mode()[0], inplace=True)
/tmp/ipykernel_30065/3345114217.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['net'].fillna(df['net'].mode()[0], inplace=True)
/tmp/ipykernel_30065/3345114217.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['types'].fillna(df['types'].mode()[0], inplace=True)
/tmp/ipykernel_30065/3345114217.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ids'].fillna(df['ids'].mode()[0], inplace=True)
/tmp/ipykernel_30065/3345114217.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sources'].fillna(df['sources'].mode()[0], inplace=True)
/tmp/ipykernel_30065/3345114217.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['type'].fillna(df['type'].mode()[0], inplace=True)

#Clean Numeric Fields

In [ ]:
df['mag'] = df['mag'].fillna(df['mag'].median()).astype(int)
df['depth_km'] = df['depth_km'].fillna(df['depth_km'].median()).astype(int)
df['nst'] = df['nst'].fillna(df['nst'].median()).astype(int)
df['dmin'] = df['dmin'].fillna(df['dmin'].median()).astype(int)
df['rms'] = df['rms'].fillna(df['rms'].median()).astype(int)
df['gap'] = df['gap'].fillna(df['gap'].median()).astype(int)
df['sig'] = df['sig'].fillna(df['sig'].median()).astype(int)

In [ ]:
df['mag error'] = df['mag error'].fillna(0).astype(int)
df['depth error'] = df['depth error'].fillna(0).astype(int)
df['magnst'] = df['magnst'].fillna(0).astype(int)

In [ ]:
df['mag-type'] = df['mag-type'].fillna(0).median()
df['location source'] = df['location source'].fillna(0).median()
df['mag source'] = df['mag source'].fillna(0).median()

#Add Derived Columns

In [ ]:
df['Year'] = df['time'].dt.year
df['month'] = df['time'].dt.month
df['day'] = df['time'].dt.day
df['day_of_week'] = df['time'].dt.day_name()

#cleaned dataset(read csv file)

In [ ]:
cleaned_data = 'earthquake data.csv'
df.to_csv(cleaned_data , index = False)

In [ ]:
df_clean = pd.read_csv('/content/earthquake data.csv')
df_clean

,id,time,updated,latitude,longitude,depth_km,mag,mag-type,place,status,...,location source,mag source,types,ids,sources,type,Year,month,day,day_of_week
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17,4,0.0,Argentina,reviewed,...,0.0,0.0,",dyfi,moment-tensor,origin,phase-data,",",us6000ddi8,",",us,",earthquake,2021,1,31,Sunday
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426,4,0.0,Alaska,reviewed,...,0.0,0.0,",origin,phase-data,",",us6000dev6,",",us,",earthquake,2021,1,31,Sunday
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46,4,0.0,Philippines,reviewed,...,0.0,0.0,",origin,phase-data,",",us6000dev5,",",us,",earthquake,2021,1,31,Sunday
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10,4,0.0,Iran,reviewed,...,0.0,0.0,",origin,phase-data,",",us6000ddhs,",",us,",earthquake,2021,1,31,Sunday
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10,4,0.0,Alaska,reviewed,...,0.0,0.0,",origin,phase-data,",",us6000dev4,",",us,",earthquake,2021,1,31,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108682,us6000sg1v,2026-03-01 00:41:53.193,2026-03-20 02:51:25.040,-10.7303,164.3618,10,4,0.0,Alaska,reviewed,...,0.0,0.0,",origin,phase-data,",",us6000sg1v,",",us,",earthquake,2026,3,1,Sunday
108683,us7000s15b,2026-03-01 00:35:07.786,2026-03-01 02:09:18.040,31.4169,131.3253,56,4,0.0,Japan,reviewed,...,0.0,0.0,",origin,phase-data,",",us7000s15b,",",us,",earthquake,2026,3,1,Sunday
108684,us7000s15a,2026-03-01 00:25:44.225,2026-03-21 22:07:39.040,-9.9104,119.9576,61,4,0.0,Indonesia,reviewed,...,0.0,0.0,",origin,phase-data,",",us7000s15a,",",us,",earthquake,2026,3,1,Sunday
108685,us6000sg1m,2026-03-01 00:22:43.082,2026-03-21 01:12:28.040,-24.0653,179.7641,537,4,0.0,Alaska,reviewed,...,0.0,0.0,",origin,phase-data,",",us6000sg1m,",",us,",earthquake,2026,3,1,Sunday
108686,us7000s159,2026-03-01 00:15:07.581,2026-03-21 21:53:45.040,51.6781,158.0044,76,4,0.0,Russia,reviewed,...,0.0,0.0,",origin,phase-data,",",us7000s159,",",us,",earthquake,2026,3,1,Sunday

In [ ]:
df.isnull().sum()

id                 0
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
mag-type           0
place              0
status             0
tsunami            0
sig                0
net                0
nst                0
dmin               0
rms                0
gap                0
mag error          0
depth error        0
magnst             0
location source    0
mag source         0
types              0
ids                0
sources            0
type               0
Year               0
month              0
day                0
day_of_week        0
dtype: int64